
  name: youtube-music-desktop
  version: '0.1' 
  
  description: This is fork of the youtube music to get you a better enhanced desktop experience. 
    
  
  Disclaimer: I do NOT own YouTube Music or MusixMatch, nor am I affiliated or even endorsed by them.
